export { default as DefaultLayout } from './DefaultLayout'
export { default as SliderLayout } from './SliderLayout'
export { default as ParallaxLayout } from './ParallaxLayout'
export { default as ProductLayout } from './ProductLayout'
export { default as AdminLayout } from './AdminLayout'
